# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  jitpack:
    type: maven-repository
    url: https://jitpack.io
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2/
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - maven-central
      - jitpack
