package macro.plan;

/** Reasons a plan is cancelled. */
public enum PlanCancelReason {
    PREREQUISITE_MISSING,
    PREREQUISITE_QUEUED_LATER,
    INSUFFICIENT_GATHERERS,
    TECH_MISSING,
    NO_LARVA,
    EXCESS_SUPPLY,
    EXCESS_HATCHERY,
    NO_MORPH_SOURCE,
    EXECUTOR_LOST,
    LARVA_DEADLOCK,
    PAIRED_PLAN_CANCELLED,
    REACTION_DEFENSE,
    REACTION_GAS_DENIED,
    REACTION_TECH_DELAYED,
    POSITION_INVALID,
    RESEARCH_INTERRUPTED,
    ALREADY_IMPOSSIBLE,
    UNKNOWN,
}
